{{ range .Values.ProjectNames }} {{- if .projectName }} {{ $Name := .projectName | lower | trimSuffix "-" }}
apiVersion: v1
kind: Namespace
metadata:
name: {{ $Name }}
annotations:
argocd.argoproj.io/sync-wave: "-1"
argocd.argoproj.io/sync-options: Prune=true,Delete=true
{{- end }}
{{ end }}
